### ISSUE TITLE
releasing v2.2

### ISSUE THREAD

**Issue by cvvergara** [anitagraser/pgRoutingLayer#20]
@anitagraser 
Hello, 
I am trying to put the v2.2 of pgRoutingLayer
I get:
```
There were errors reading plugin package (please check also your plugin's metadata).
The name of the top level directory inside the zip package must start with an ASCII letter and can only contain ASCII letters, digits and the signs '-' and '_'.
```

Working on "new version for plugin"
Ticked the experimental.
I downloaded the zip file from here:
https://github.com/pgRouting/pgRoutingLayer/releases/tag/v2.2.0
into my computer
Then I used the <browse> button to select the file
Left the change log empty because it will read it from the meta:
https://github.com/pgRouting/pgRoutingLayer/blob/v2.2.0/metadata.txt

So what am I doing wrong?

Can you help me please.

Vicky

**Comment by anitagraser** [comment]
Hi Vicky,

When I download the ZIP through that URL, the folder inside is called
pgRoutingLayer-2.2.0. Instead, it has to be pgRoutingLayer. The plugin
platform is picky that way.

Regards,
Anita

**Comment by cvvergara** [comment]
Thanks for the info, 
I modified the name, and I could upload it :)
Its waiting for the approval

Thanks again

Vicky
