### ISSUE TITLE
pgroutinglayer broken in QGIS 2.3 master

### ISSUE THREAD

**Issue by ani82** [anitagraser/pgRoutingLayer#8]
Dear Anita,

when using your plugin in 2.3.0-Master (out of the QGIS repo) on Ubuntu 12LTS I don't get a result displayed. The execution for Dijkstra seems to be interrupted with the following warning:

warning:/home/alex/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py:389: DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated
  args['canvas_srid'] = Utils.getCanvasSrid(Utils.getDestinationCrs(self.iface.mapCanvas().mapRenderer()))

traceback:

Running the same query via pgadmin returns the normal routing list. Seems like the step for adding the routing result to the project is broken.

**Comment by anitagraser** [comment]
@sanak can this issue be closed?

**Comment by sanak** [comment]
@anitagraser 
I fixed it on the following commit.
https://github.com/pgRouting/pgRoutingLayer/commit/861a43e058c1fc01f8bd1f69a9d496bce5251ba2
But, the branch needs more effort to support pgRouting 2.1...
Sorry for my slow work.

**Comment by anitagraser** [comment]
Thanks for the update, no problem! I'll open a dedicated ticket for pgRouting >= 2.1

**Comment by ani82** [comment]
Thanks for your efforts!
