### ISSUE TITLE
tsp_euclid showing no results

### ISSUE THREAD

**Issue by robrichter** [anitagraser/pgRoutingLayer#9]
Tsp_euclid algorithm ends with no results and even without any error message. I tested it on Czech republic road network and then on test data from pgrouting web (http://docs.pgrouting.org/dev/doc/src/developer/sampledata.html). Both with no results. 

I tried it on QGIS version 2.4.0 on Ubuntu Trusty and OpenSuse 13.1 (both 64bit). But I think error is not version dependant. It may be something wrong with the sql in pgRoutingLayer plugin. I copied the sql statement from pgRoutingLayer to command line. It gave me 0 results. You can see the sql example below. 

SELECT seq, id1 AS internal, id2 AS node, cost FROM pgr_tsp('
               SELECT DISTINCT id, x, y FROM
                   (SELECT DISTINCT source AS id, x1::float8 AS x, y1::float8 AS y FROM edge_table
                   UNION
                   SELECT DISTINCT target AS id, x2::float8 AS x, y2::float8 AS y FROM edge_table)
                   AS node WHERE node.id IN (7,8,11)',
               2, 12)

**Comment by anitagraser** [comment]
Seems like this is resolved. Please reopen if necessary.
